#!/bin/bash
sbatch --account=astro --job-name=basta_run --output=slurm_%j.out --error=slurm_%j.err --time=40:00:00 --mem=60000 --nodes=1 --ntasks=1 --cpus-per-task=32 --constraint=blade --qos=long "$@"
